CREATE TABLE GoldPrices (
    PriceID INT PRIMARY KEY AUTO_INCREMENT,
    GoldPrice DECIMAL(10, 2),
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
);

INSERT INTO GoldPrices (GoldPrice) VALUES (5000.00);
CREATE TABLE GoldPriceLog (
    LogID INT PRIMARY KEY AUTO_INCREMENT,
    OldPrice DECIMAL(10, 2),
    NewPrice DECIMAL(10, 2),
    ChangedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DELIMITER $$
CREATE TRIGGER LogGoldPriceChange
BEFORE UPDATE ON GoldPrices
FOR EACH ROW
BEGIN
    INSERT INTO GoldPriceLog (OldPrice, NewPrice)
    VALUES (OLD.GoldPrice, NEW.GoldPrice);
END$$
DELIMITER ;

UPDATE GoldPrices SET GoldPrice = 5200.00 WHERE PriceID = 1;
SELECT * FROM GoldPriceLog;
